copy_all
    scp ./*.py root@51.250.126.51:/tmp/mapreduce/ && scp ./run.sh root@51.250.126.51:/tmp/mapreduce/

copy_run
    scp ./run.sh root@51.250.126.51:/tmp/mapreduce/

copy_py
    scp ./*.py root@51.250.126.51:/tmp/mapreduce/

copy_local
    scp root@51.250.126.51:taxi-output/* /home/user/dawnload
